### ISSUE TITLE
Implement Creation of Projects

### ISSUE THREAD

**Issue by Fire30** [sdavies514/CS3754-Semester-Project#19]
Need a page that will let us create a project with a name and a password.

**Comment by Fire30** [comment]
Should we just use the generated JSF pages for creation and joining of a project, or create our own pages?

**Comment by Fire30** [comment]
I think the generated jsf pages should work tbh, can list all projects, and then have two buttons at bottom, one for join the selected, and then one for create.

**Comment by Fire30** [comment]
If you go /project/List.xhtml you can create and join projects now. When you create a project the Project table gets updated with a new entry, when you join with a correct password a UserProjectAssociation entry is created.

**Comment by cjbvt** [comment]
I think this issue is basically done, so can we close it?
