### ISSUE TITLE
Identify Data Tables

### ISSUE THREAD

**Issue by cjbvt** [sdavies514/CS3754-Semester-Project#4]
Just make comments on this issue identifying all the data tables we need.

**Comment by Fire30** [comment]
Ok I am not really a database person, but I think the tables we will need will be something like:

- User
- Project
- Milestone
- Message (Chat)
- File
- CompletedActivities (For RSS Feed, Heatmap, etc)

And I guess we will need ways to relate the users to a project and vice versa,

**Comment by cjbvt** [comment]
We came to some conclusions about this at our meeting today so I'm closing it.
