### ISSUE TITLE
Obtain client ID and client secret from Google

### ISSUE THREAD

**Issue by cjbvt** [sdavies514/CS3754-Semester-Project#7]
These are required by our OpenID Connect (OIDC) feature. We must register our application with Google's authentication server in order to get them.

> Before your application can use Google's OAuth 2.0 authentication system for user login, you must set up a project in the [Google API Console](https://console.developers.google.com/) to obtain OAuth 2.0 credentials, set a redirect URI, and (optionally) customize the branding information that your users see on the user-consent screen.

https://developers.google.com/identity/protocols/OpenIDConnect

**Comment by sdavies514** [comment]
Google login has been implemented.  I'll start the writeup today.
