### ISSUE TITLE
Implement PrimeFaces Push chat

### ISSUE THREAD

**Issue by cjbvt** [sdavies514/CS3754-Semester-Project#8]
This feature is described in [PrimeFaces Showcase](https://www.primefaces.org/showcase/push/chat.xhtml) and referenced in chapter 9 of the [PrimeFaces 6.1 user guide](https://www.primefaces.org/docs/guide/primefaces_user_guide_6_1.pdf). This task is simply to get a basic demo working, it doesn't necessarily need to hook into our user management system or anything yet.

**Comment by Fire30** [comment]
I do this tomorrow/wednesday.

**Comment by Fire30** [comment]
ok so was busy with holiday stuff and had to wait to implement it. 

Got the sample real time chat application working with commit 6411e74c2b02f56bf2f2479e3e8eb5c23e0dcfa6, however had to make a decent amount of changes that they decided not to document :/ except for on random issues on github lol(https://github.com/Atmosphere/atmosphere/issues/2067#issuecomment-153009336) 

I'll continue working on it to try to make it look a tad nicer and work with our database schema, etc. 

Also I will need to update the file structures, cause currently all the files are in there own chat package which isn't right either.

**Comment by Fire30** [comment]
Oh and somehow the use of the PrimeFaces PushServlet makes the startup of our application racy. It will sometimes fail to start with the error:

Warning:   java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: The urlPattern must start with '/'
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: The urlPattern must start with '/'
