### ISSUE TITLE
Create the database tables described in the ER diagram

### ISSUE THREAD

**Issue by cjbvt** [sdavies514/CS3754-Semester-Project#9]
One exception: we're storing passwords in OpenBSD format so we don't need to store the salt and hash separately.

**Comment by td2304** [comment]
I can work on this.

**Comment by Fire30** [comment]
Ok soI went ahead and created the Project and Message tables, as they are needed for the real time chat part. Once again I am not a db person so I was wondering if this would look ok? If so I'll commit.

```
CREATE TABLE Project
(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR (256) NOT NULL
);

CREATE TABLE Message
(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    message_text VARCHAR (10000) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    project_id INT UNSIGNED,
    FOREIGN KEY (project_id) REFERENCES Project(id) ON DELETE CASCADE,
    user_id INT UNSIGNED,
    FOREIGN KEY (user_id) REFERENCES User(id)
);
```

**Comment by cjbvt** [comment]
I think we're gonna need a password_hash column on the project table, but otherwise looks fine

**Comment by td2304** [comment]
Sorry about not having an update on this, I've been really swamped with work all of last week. I'll have this done as soon as I can (coinciding with other deadlines)

**Comment by cjbvt** [comment]
It sounds like it's practically done already.

**Comment by Fire30** [comment]
Ok started with this commit. 

984cb360d7f5ab55e8d969d49d36a2add8764ddf

Put it on feature/9 branch so once again people can look. I added the hashed_password field as well.

**Comment by Fire30** [comment]
So I ended up needing to make more and more tables to do real time chat, so I ended up just creating all the tables and their various entity and facade beans. I also committed the changes to develop.

commit is ddd79fc900474bd497b5637a085be92f5780110b
